// Browser / Capacitor / React Native entry — omits @ipfs-meshkit/node
// (child_process, path) and the Node.js-only init / shutdown helpers.
export type {
  MeshkitClient,
  MeshkitConfig,
  MeshkitInitOptions,
  StoredObject,
  IpnsDuration,
  IpnsKey,
  IpnsKeyGenOptions,
  IpnsPublishOptions,
  IpnsPublishResult,
  IpnsResolveOptions,
  GatedAccessOperation,
  MeshkitGatedAccessConfig,
  MeshkitGatedAccessWallet,
  MeshkitPptNetwork,
  ResolvedGatedAccess,
  AssertGatedAccessResult,
  GatedAccessErrorCode,
  GatedAccessErrorDetails,
  PptNetworkPreset,
  S3StorageConfig,
  FilOneConfig,
} from '@ipfs-meshkit/core';
export {
  MeshkitError,
  Meshkit,
  createMeshkitClient,
  createS3Client,
  createFilOneClient,
  IPNS_TTL_DEFAULT,
  IPNS_TTL_FAST,
  extractCidFromPath,
  toIpfsPath,
  toIpnsPath,
  assertGatedAccess,
  resolveGatedAccess,
  resolveFee,
  GatedAccessError,
  PPT_NETWORKS,
  DEFAULT_PPT_NETWORK,
} from '@ipfs-meshkit/core';
